#!/bin/sh
git submodule foreach git checkout master
git submodule foreach git fetch
git submodule foreach git pull origin master

git submodule foreach git submodule foreach git checkout master
git submodule foreach git submodule foreach git fetch
git submodule foreach git submodule foreach git pull origin master
